language: c

compiler: gcc

env:
  - OMP_NUM_THREADS=4

include:
  # works on Precise and Trusty
  - os: linux
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-4.9
    env:
       - MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"

  # works on Precise and Trusty
  - os: linux
    addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++-5
    env:
       - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"

before_install:
  - eval "${MATRIX_EVAL}"

script: make
